name: Python application

on: [push]  # Ejecuta las pruebas en cada 'push' (cambio) que subas

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un servidor Linux en GitHub para ejecutar las pruebas

    steps:
    - uses: actions/checkout@v2  # Descarga el código del repositorio
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Define la versión de Python (por ejemplo, '3.8' o '3.10')
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias de requirements.txt
    - name: Run tests
      run: |
        pytest  # Ejecuta pytest para correr las pruebas unitarias
